version: "3.8"
services:
  vtv-app-web:
    image: felwitcher/vtv-app-web:latest
    ports:
      - "5173:80"
    depends_on:
      - vtv-app-api

  vtv-app-api:
    image: felwitcher/vtv-app-api:latest
    ports:
      - "5233:80"
